chore(mirror): logging and error handling improvements (#14535)
This PR address traffic generator (aka mirror) crashing with 160684617
image.

The initial error is:
```
thread 'tokio-runtime-worker' panicked at tools/mirror/src/lib.rs:1744:46:
called `Result::unwrap()` on an `Err` value: SendError { .. }
```
This is not a real issue, but early panic caused node crash without
logging the actual error. This is addressed by returning error instead
of unwrapping when `send` fails.

When final select in run function finishes receivers of some senders
there are passed into spawned coroutines would be deallocated. This
would cause send on those senders to return error. Since we were
unwrapping before this change it would cause panic. This panic would
show that some values weren't able to be send, but have no information
about what is causing that - which is a reason why run finished and
deallocated relevant receivers.

If we instead don't unwrap on send it should give opportunity for the
run function result propagating and hopefully showing relevant result.