fix: Cargo Audit CI check
Sample error: /github.com/near/nearcore/actions/runs/20774499254/job/59657059995?pr=14844

```
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
error: error loading advisory database: parse error: error parsing /home/runner/.cargo/advisory-db/crates/cap-primitives/RUSTSEC-2024-0445.md: parse error: TOML parse error at line 8, column 8
  |
8 | cvss = "CVSS:4.0/AV:N/AC:L/AT:P/PR:L/UI:N/VC:L/VI:L/VA:L/SC:N/SI:N/SA:N"
  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
unsupported CVSS version: 4.0
```

Suport for CVSS version 4 was added in cargo audit here
https://github.com/rustsec/rustsec/releases/tag/cargo-audit%2Fv0.22.0,
see related
https://github.com/rustsec/rustsec/releases/tag/cvss%2Fv2.2.0