fix: don't type convert errors to strings unnecessary
I *think* the old code caused the following flaky failure for me from
time to time:

thread 'tests::client::process_blocks::access_key_nonce_range_tests::test_chunk_transaction_validity' panicked at \
  'assertion failed: `Other("Invalid Transactions")` does not match `Error::InvalidTransactions`', \
  integration-tests/src/tests/client/process_blocks.rs:3811:9

failures:
    tests::client::process_blocks::access_key_nonce_range_tests::test_chunk_transaction_validity

Note that this might be a behavior-changing change. I don't know the
surrounding code well enough to judge whether this is problematic. But
the current code does look very much like a bug.