test: fix test loop missing chunk example compilation (#13167)
With #13161 test-loop-tests build fails when `test_features` is not
enabled:
```
% cargo test -p test-loop-tests -- global_contracts
error[E0432]: unresolved import `near_client::NetworkAdversarialMessage`
  --> test-loop-tests/src/examples/missing_chunk.rs:4:5
   |
4  | use near_client::NetworkAdversarialMessage;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `NetworkAdversarialMessage` in the root
   |
```