doc: fix "Deploy a contract" documentation (#13714)
- remove misplaced `$` in `near` invocation examples
- mark `extern "C"` as `unsafe`, which seems to be required in `cargo
1.87.0 (99624be96 2025-05-06)`:
```
error: extern blocks must be unsafe
 --> src/lib.rs:3:1
  |
3 | / extern "C" {
4 | |     fn value_return(len: u64, ptr: u64);
5 | | }
  | |_^

error: could not compile `hello-near` (lib) due to 1 previous error
```

---------

Signed-off-by: Roman Volosatovs <roman@cosmonic.com>