tests: Disable precompilation test on aarch64-apple
As it fails with:
```
thread 'tests::test_contract_precompilation' panicked at 'Compilation result should be non-empty', runtime/runtime/src/lib.rs:2550:14
```
presumably because compilation cache is not populated on aarch64-apple.