doc(profiling): use correct `read-write` flag (#13746)
Possibly this flag was renamed, but `readwrite` is not a valid flag in
recent `neard` versions:
```
error: unexpected argument '--readwrite' found

  tip: a similar argument exists: '--read-write'

Usage: neard view-state <--read-write|--store-temperature <STORE_TEMPERATURE>> <COMMAND>
```

Signed-off-by: Roman Volosatovs <roman@cosmonic.com>