fix: JSON RPC Primitives with default features (#8606)
Building this was just broken, I don't know for how long.
It was now caught when publishing crates, because you can't publish
with compilation errors.


error:
```
error[E0433]: failed to resolve: use of undeclared crate or module `near_client_primitives`
 --> chain/jsonrpc-primitives/src/types/status.rs:1:5
  |
1 | use near_client_primitives::debug::{
  |     ^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `near_client_primitives`
```