fix(CI) - fix the check_build_public_libraries workflow (#12357)
It looks like the "Windows check for building public libraries" CI check
was broken by https://github.com/near/nearcore/pull/12341

Running `just check_build_public_libraries` produced errors and
warnings:
```
cargo check -p near-primitives -p near-crypto -p near-jsonrpc-primitives -p near-chain-configs -p near-primitives-core
    Checking near-primitives v0.0.0 (/home/jan/code/nearcore/core/primitives)
error[E0432]: unresolved import `crate::reed_solomon`
  --> core/primitives/src/stateless_validation/contract_distribution.rs:10:12
   |
10 | use crate::reed_solomon::{ReedSolomonEncoderDeserialize, ReedSolomonEncoderSerialize};
   |            ^^^^^^^^^^^^ could not find `reed_solomon` in the crate root
   |
note: found an item that was configured out
  --> core/primitives/src/lib.rs:30:9
   |
30 | pub mod reed_solomon;
   |         ^^^^^^^^^^^^
note: the item is gated behind the `solomon` feature
  --> core/primitives/src/lib.rs:29:7
   |
29 | #[cfg(feature = "solomon")]
   |       ^^^^^^^^^^^^^^^^^^^

error[E0432]: unresolved import `crate::reed_solomon`
  --> core/primitives/src/stateless_validation/state_witness.rs:8:12
   |
8  | use crate::reed_solomon::{ReedSolomonEncoderDeserialize, ReedSolomonEncoderSerialize};
   |            ^^^^^^^^^^^^ could not find `reed_solomon` in the crate root
   |
note: found an item that was configured out
  --> core/primitives/src/lib.rs:30:9
   |
30 | pub mod reed_solomon;
   |         ^^^^^^^^^^^^
note: the item is gated behind the `solomon` feature
  --> core/primitives/src/lib.rs:29:7
   |
29 | #[cfg(feature = "solomon")]
   |       ^^^^^^^^^^^^^^^^^^^

warning: unused import: `ShardId`
  --> core/primitives/src/block.rs:18:35
   |
18 | use near_primitives_core::types::{ShardId, ShardIndex};
   |                                   ^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default
```

The main problems is that there's code that requires the `solomon`
feature to be enabled, but it isn't guarded behind a `cfg(feature)`, so
the compilation fails when the feature isn't enabled.