fix: SweatUser has no attribute 'sweat' (#9411)
Fixes `AttributeError: 'SweatUser' object has no attribute 'sweat'` error on Sweatcoin loadtest. Was introduced by mistake in this place: https://github.com/near/nearcore/pull/9385/files#diff-dd0c2c70c41c997fd0cb86472624ed02f913c6b3ba0e4a1a26b18d429449ee34L59