fix(locust): wait for base on_locust_init() to finish before other init fns
the base on_locust_init() function sets
`environment.master_funding_account`, and other init functions expect
it to be set when they're run. When that isn't the case, you can get
this sort of error:

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/locust/event.py", line 40, in fire
    handler(**kwargs)
  File "/home/ubuntu/nearcore/pytest/tests/loadtest/locust/common/social.py", line 261, in on_locust_init
    funding_account = environment.master_funding_account
AttributeError: 'Environment' object has no attribute 'master_funding_account
```

This error can even happen in the master, before the workers have been
started, and it might be related to this issue (which has been closed
due to inactivity):
https://github.com/locustio/locust/issues/1730. That bug mentions that
`User`s get started before on_locust_init() runs, but maybe for similar
reasons, we can't guarantee the order in which each on_locust_init()
function will run.  This doesn't seem to happen every time, and it
hasn't really been triggered on MacOS, only on Linux. But this makes
it kind of a blocker for setting this test up on cloud VMs (where this
bug has been observed)