Revert "feature: Implement compute usage aggregation and limiting (#8805)"
This reverts commit 700ec29270f72f2e78a17029b4799a8228926c07.

Canary nodes found an issue with this change:
```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `2519443987198`,
 right: `2429311750949`: Compute usage must match burnt gas',
```