feat(tests): test loop for promise yield receipts in reshardingV3 (#12582)
Adding two new tests for resharding V3:
- `test_resharding_v3_yield_resume`: tests promise-yield receipts
created before the resharding block and resumed after. It works out of
the box.
- `test_resharding_v3_yield_timeout`: tests promise-yield receipts
created before the resharding block and timing out after. Doesn't work
when the account belongs to the parent shard. Failure is:
  ```
10.556s DEBUG clear_data: garbage_collection: GC block_hash
gc_mode=GCMode::Canonical
  block_hash=J5MyhbZDtgNFofZ1DrWYbh4f8MDLaBkAeRSmkerQFuM1
10.556s DEBUG clear_data:ChainStoreUpdate::commit:ChainUpdate::finalize:
store: close time.busy=10.5µs
  time.idle=374ns
thread
'test_loop::tests::resharding_v3::test_resharding_v3_yield_timeout'
panicked at core/store/src/db/testdb.rs:100:25:
  Inserting value with non-positive refcount
note: run with `RUST_BACKTRACE=1` environment variable to display a
backtrace
10.557s DEBUG clear_data:ChainStoreUpdate::commit: store: close
time.busy=725µs time.idle=417ns
10.557s DEBUG clear_data: garbage_collection: close time.busy=1.72ms
time.idle=500ns
  ```
Haven't looked deeply into the error, might be similar to the delayed
receipts issue.

Minor refactoring to avoid excessive code duplication.