fix: fix 12 -> 13 migration (#3676)
This was a one-off fix done a while ago but somehow wasn't merged into master. Some partners ran into the same issue so it makes sense to merge this to master. The issue is that the migration can fail due to
```
thread 'main' panicked at 'unexpected error during migration, IO Error: Not all bytes read
 Cause: Unknown', neard/src/migrations.rs:102:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
and I realized that the logic there is not actually needed since we only care about the canonical chain when migrating past data.