view-state: fix rocksdb-stats command
sst_dump’s --file argument requires a path to a single SST file.
Alas, get_rocksdb_stats tried to pass it path to the directory
containing the entire RocksDB database.  This unsurprisingly lead to
failures such as:

    $ ./target/debug/neard view-state rocksdb-stats
    ....
    thread 'main' panicked at 'Couldn't get RocksDB stats: failed to run sst_dump, exit status: 1, stderr: No valid SST files found in /home/mpn/.near/data

Fix the function by iterating over SST files in the directory.

While at it, take configuration read from config.json into account
when figuring out the path to the database.