chore: update rocksdb dependency to 0.22 (#12672)
Updating rocksdb to 0.22 allows us to remove the run-time CStr → str
conversion when collecting statistics.

rocksdb is at 0.23 however I got dependency resolution failure when
trying to update to that version (included below). Since 0.22 is enough
to resolve one of my TODOs, my job here is done. ;)

    error: failed to select a version for `tikv-jemalloc-sys`.
        ... required by package `tikv-jemallocator v0.5.4`
... which satisfies dependency `tikv-jemallocator = "^0.5.0"` of package
`neard v0.0.0 (…)`