pytest: restaked: wait for at least one block to be generated
This reduces flakiness of the sanity/restaked.py test though does
not fix it completely.  It resolves failures caused by UNKNOWN_EPOCH
error such as:

    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value:
    "RpcError { error_struct: Some(HandlerError(Object({\"name\": String(\"UNKNOWN_EPOCH\")}))),
                code: -32000,
                message: \"Server error\",
                data: Some(String(\"Unknown Epoch\")) }"', tools/restaked/src/main.rs:86:48

There’s still an issue where restake tool will send StakeAction which
is never executed.  This can be observed by there being only two attempts
at staking as in:

    INFO: Starting restaked for /home/mpn/.near/test0, rpc = 0.0.0.0:3041
    INFO  restaked] Sending staking transaction test0 -> 50000000000000000000000000000000
    INFO  restaked] Sending staking transaction test0 -> 50000000000000000000000000000000
    Traceback (most recent call last):
      File "/home/mpn/code/near/nearcore/pytest/tests/sanity/restaked.py", line 79, in <module>
        assert False, "Validator test0 is not in current validators after 5 epochs"
    AssertionError: Validator test0 is not in current validators after 5 epochs

Fixes: https://github.com/near/nearcore/issues/5767