Cover cargo build failures in buildkite/nearcore (#4368)
Attempt to solve https://github.com/near/nearcore/issues/4367

Check both stable and nightly `cargo build -p neard`

Checked that it covers previous commit:
```
$ git checkout 377908d18e0d4ed46eab2f0cdabf3f9a648179e3
$ cargo check -p neard --features nightly_protocol,nightly_protocol_features
error: failed to select a version for `near-client`.
    ... required by package `nearcore v1.2.0 (/home/Aleksandr1/nearcore/nearcore)`
    ... which is depended on by `neard v1.2.0 (/home/Aleksandr1/nearcore/neard)`
versions that meet the requirements `=0.1.0` are: 0.1.0

the package `nearcore` depends on `near-client`, with features: `nearcore` but `near-client` does not have these features.
```