refactor: fix clippy deprecated since warning (#8158)
Fixes the following clippy error:
```
error: the since field must contain a semver-compliant version
   --> core/account-id/src/lib.rs:302:18
    |
302 |     #[deprecated(since = "#4440", note = "AccountId construction without validation is illegal")]
    |                  ^^^^^^^^^^^^^^^
    |
    = note: `#[deny(clippy::deprecated_semver)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#deprecated_semver
```