fix(runtime): revert implicit account creation on account deletion (#4512)
In #4169, we introduced a protocol feature that allows implicit account to be created as the beneficiary of some account deletion action. However, this caused testnet to crash at block 55178321 with the following error:
```
Jul 13 22:44:25 testnet-nearup4 sh[21330]: thread 'main' panicked at 'Balance Mismatch Error. The input balance 2001150137400703804480000 doesn't match output balance 2001192864617753804480000
Jul 13 22:44:25 testnet-nearup4 sh[21330]: Inputs:
Jul 13 22:44:25 testnet-nearup4 sh[21330]:         Incoming validator rewards sum: 0
Jul 13 22:44:26 testnet-nearup4 sh[21330]:         Initial accounts balance sum: 2000043837364131900000000
Jul 13 22:44:26 testnet-nearup4 sh[21330]:         Incoming receipts balance sum: 1106300036571904480000
Jul 13 22:44:26 testnet-nearup4 sh[21330]:         Processed delayed receipts balance sum: 0
Jul 13 22:44:26 testnet-nearup4 sh[21330]:         Initial postponed receipts balance sum: 0
Jul 13 22:44:26 testnet-nearup4 sh[21330]: Outputs:
Jul 13 22:44:26 testnet-nearup4 sh[21330]:         Final accounts balance sum: 2000092621719357300000000
Jul 13 22:44:26 testnet-nearup4 sh[21330]:         Outgoing receipts balance sum: 743618847456404480000
Jul 13 22:44:26 testnet-nearup4 sh[21330]:         New delayed receipts balance sum: 0
Jul 13 22:44:26 testnet-nearup4 sh[21330]:         Final postponed receipts balance sum: 0
Jul 13 22:44:26 testnet-nearup4 sh[21330]:         Tx fees burnt amount: 356624050940100000000
Jul 13 22:44:26 testnet-nearup4 sh[21330]:         Slashed amount: 0
Jul 13 22:44:26 testnet-nearup4 sh[21330]:         Other burnt amount: 0', nearcore/src/runtime/mod.rs:468:58
```

Upon closer analysis, I found that in this block there is exactly one receipt and no transaction contained in this block:
```
Receipt { predecessor_id: "caf7949de4fa4a61fd5d4d71c171560e49ad64e35221b01050ddf81a452a61cb", recei
ver_id: "htlc-59b17c7cbe94a6ff0ad4-1626190787713", receipt_id: `4dt4tsostyU9XxJ3tPfjZw7WQiXTrKq5KyG5HLJrqW1U`, receipt: Action(ActionReceipt { signer_id: "caf7949de4fa4a61fd5d4d71c171560e49ad64e35221b01050ddf81a452a61cb", signer_public_key: ed25519:EfJKMTn3B3dv5ktJFgkFMK36TtHTEUnCqmGP5EtUq4vE, gas_price: 106090000, output_data_receivers: [], input_data_ids: [], actions: [FunctionCall(FunctionCallAction { method_name: refund, args: `{}`, gas: 8000000000000, deposit: 0 })
```
This receipt generates two receipts:
```
outgoing receipts: [Receipt { predecessor_id: "htlc-59b17c7cbe94a6ff0ad4-1626190787713", receiver_id: "htlc-59b17c7cbe94a6ff0ad4-1626190787713", receipt_id: `3yatvtxgTpJqZEr6JPe1YkkjfzZYE8QVDV3p5gBSuJGY`, receipt: Action(ActionReceipt { signer_id: "caf7949de4fa4a61fd5d4d71c171560e49ad64e35221b01050ddf81a452a61cb", signer_public_key: ed25519:EfJKMTn3B3dv5ktJFgkFMK36TtHTEUnCqmGP5EtUq4vE, gas_price: 106090000, output_data_receivers: [], input_data_ids: [], actions: [DeleteAccount(DeleteAccountAction { beneficiary_id:
"caf7949de4fa4a61fd5d4d71c171560e49ad64e35221b01050ddf81a452a61cb" })] }) }, Receipt { predecessor_id: "system", receiver_id: "caf7949de4fa4a61fd5d4d71c171560e49ad64e35221b01050ddf81a452a61cb", receipt_id: `9J53AZ6bNViL6dzYZiNwjj1p19QBNAKNGtCXfFwdTveX`, receipt: Action(ActionReceipt { signer_id: "caf7949de4fa4a61fd5d4d71c171560e49ad64e35221b01050ddf81a452a61cb", signer_public_key: ed25519:EfJKMTn3B3dv5ktJFgkFMK36TtHTEUnCqmGP5EtUq4vE, gas_price: 0, output_data_receivers: [], input_data_ids: [], actions: [Transfer(TransferAction { deposit: 673780490041404480000 })] }) }]
```
and one of them contains an account deletion action. This led to me suspect that #4169 broke the balance invariant when handling account deletions. I tried reverting the change and the node was then able to process the chunk without issues. While I did not have time to closely inspect the logic and figure out where exactly the balance mismatch happened, it is good enough to revert #4169 for now so that we do not get blocked on it.

Note: it is intentional that this does not go through the normal protocol upgrade process since 1) testnet already crashed and 2) the bug means that a node will crash when process a receipt containing such an action, which won't cause state to diverge and it makes sense to change the behavior directly.

Test plan
---------
Existing tests