fix: avoid infinite loop in estimator
When all accounts have been used and an estimation requests
an unsued account, the estimator panics instead of hanging in an
infinite loop.

Example error:

```
thread 'main' panicked at 'All accounts used. Try running with a higher value for the parameter `--accounts-num <NUM>`.', runtime/runtime-params-estimator/src/transaction_builder.rs:99:13
```

resolves #7448