resolve wasmer0 and wasmtime conflict
Specifically, without this hack we get

  thread 'tests::runtime_errors::test_address_overflow' panicked at 'not within a catch_unsafe_unwind scope', /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-runtime-core-near-0.18.2/src/fault.rs:227:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I assume that is because both wasmtime and wasmer0 install signal
handlers simultaneously.